# Generated by Django 4.1.5 on 2023-01-07 08:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('emblem', models.ImageField(upload_to='media/emblems/%y/%m/%d')),
                ('shape', models.TextField()),
                ('area', models.FloatField(help_text='Squared Area in Km')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Example : [ar ,en,es]', max_length=3, unique=True, verbose_name='Language Code')),
                ('country_code', models.CharField(help_text='Example : [eg ,gb,sa,de]', max_length=3)),
                ('name', models.TextField()),
                ('dir', models.CharField(choices=[('rtl', 'Right to Left'), ('ltr', 'Left to Right')], max_length=3)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GovernorateLanguageBased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('governor', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True)),
                ('gov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governorates', to='system.governorate', verbose_name='governorate')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.language', verbose_name='language')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('gov', 'lang')},
            },
        ),
    ]
