# Generated by Django 4.1.5 on 2023-02-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='governorate',
            name='theme',
            field=models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('red', 'Red'), ('brown', 'Brown')], default='blue', max_length=10),
            preserve_default=False,
        ),
    ]
