# Generated by Django 4.1.5 on 2023-02-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_governorate_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='governorate',
            name='population',
            field=models.IntegerField(default=0),
        ),
    ]
