# Generated by Django 4.1.5 on 2023-04-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_event_eventlanguagebased'),
    ]

    operations = [
        migrations.RenameField(
            model_name='governorate',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='governoratelanguagebased',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='landmarklanguagebased',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.RemoveField(
            model_name='landmark',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='landmark',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='event',
            name='isMain',
            field=models.BooleanField(default=False, verbose_name='Main'),
        ),
        migrations.AlterField(
            model_name='eventlanguagebased',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
