# Generated by Django 4.1.5 on 2023-04-04 08:41

from django.db import migrations, models
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_rename_eventlanguagebased_landmarkeventlanguagebased_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmark',
            name='image',
            field=models.ImageField(upload_to=system.models.LandmarkImagesPath),
        ),
    ]
