# Generated by Django 4.1.5 on 2023-04-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_rename_gov_governoratelanguagebased_govobject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landmark',
            old_name='governorate',
            new_name='govObject',
        ),
    ]
