# Generated by Django 4.1.5 on 2023-04-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_rename_governorate_landmark_govobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmarklanguagebased',
            name='founder',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
