# Generated by Django 4.1.5 on 2023-04-04 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_alter_landmarklanguagebased_founder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmarklanguagebased',
            name='landmarkObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.landmark', verbose_name='landmark'),
        ),
    ]
