# Generated by Django 4.1.5 on 2023-04-22 15:02

from django.db import migrations, models
import django.db.models.deletion
import system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_alter_landmarklanguagebased_landmarkobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourismCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, unique=True)),
                ('image', models.ImageField(upload_to=system.models.TourismCategoryImagesPath)),
            ],
        ),
        migrations.AlterField(
            model_name='governorate',
            name='name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='name',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='landmarkevent',
            name='name',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='TourismTypesLandmarkList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.tourismcategory', verbose_name='core')),
                ('landmarkObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.landmark', verbose_name='landmark')),
            ],
        ),
        migrations.CreateModel(
            name='TourismCategoryLanguageBased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('categoryObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.tourismcategory', verbose_name='core')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.language', verbose_name='language')),
            ],
        ),
    ]
